
package vista;

import controlador.ControladorMesaRuleta;
import dominio.Jugador;
import dominio.ruleta.MesaRuleta;
import java.math.BigDecimal;


public class PanelDatosRuleta extends javax.swing.JPanel implements IVistaDatosRuleta{

       ControladorMesaRuleta controladorMesa;
       Jugador jugador;
       MesaRuleta mesaRuleta;
       BigDecimal saldoInicial;
  
    public PanelDatosRuleta(Jugador u, MesaRuleta m) {
        initComponents(); 
        jugador =u;
        mesaRuleta = m;
        lblJugador.setText("Jugador: " + jugador.getNombreUsuario());
        lblSaldo.setText("Saldo: " + jugador.getSaldo());
        lblGanancia.setText("Ganancia: Aun no ha jugado!");
        saldoInicial = jugador.getSaldo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApuesta = new javax.swing.JLabel();
        montoApuesta = new javax.swing.JSpinner();
        btnJugar = new javax.swing.JButton();
        btnRepetirApuesta = new javax.swing.JButton();
        lblJugador = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblGanancia = new javax.swing.JLabel();

        lblApuesta.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        lblApuesta.setText("Apuesta");

        btnJugar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnRepetirApuesta.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        btnRepetirApuesta.setText("Repetir apuesta");

        lblJugador.setText("Jugador");

        lblSaldo.setText("Saldo: ");

        lblGanancia.setText("Ganancia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(montoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnRepetirApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugador)
                    .addComponent(lblSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGanancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRepetirApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugarActionPerformed

    @Override
    public void mostrar(MesaRuleta mesa, Jugador usu) {
       lblSaldo.setText("Saldo: " + jugador.getSaldo());
       BigDecimal resta = saldoInicial.subtract(jugador.getSaldo());
       lblGanancia.setText("Ganancia: " + resta);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRepetirApuesta;
    private javax.swing.JLabel lblApuesta;
    private javax.swing.JLabel lblGanancia;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JSpinner montoApuesta;
    // End of variables declaration//GEN-END:variables

    
}
